services:
  # etcd service
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: etcd_pixiu
    environment:
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd_pixiu:2379
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_NAME=etcd-node-1
    volumes:
      - ./etcd-data:/etcd-data
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - app_network

  mysql_pixiu:
    image: mysql:8
    container_name: mysql_pixiu
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: pixiu
      MYSQL_USER: pixiu_user
      MYSQL_PASSWORD: pixiu_password
    ports:
      - "3306:3306"
    volumes:
      - ./pkg/resources/sql:/docker-entrypoint-initdb.d
    networks:
      - app_network

  # backend service(GO)
  backend:
    image: golang:1.22
    container_name: go_backend
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8081:8081"
    command: >
      sh -c "
        curl -sS http://etcd_pixiu:2379/health || exit 1 &&
        go mod tidy &&
        go run ./cmd/admin/admin.go -c docker-config.yaml
      "
    environment:
      - GO111MODULE=on
      - GOPROXY=https://goproxy.cn,direct
    networks:
      - app_network
    depends_on:
      - etcd

  # frontend（Web）
  frontend:
    image: node:18
    container_name: frontend
    working_dir: /app/web
    volumes:
      - ./web:/app/web
    ports:
      - "8080:8080"
    command: >
      sh -c "
        yarn install &&
        yarn run serve --host 0.0.0.0
      "
    networks:
      - app_network
    depends_on:
      - backend

networks:
  app_network:
    driver: bridge